name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run go tests
        run: go test -cover ./...

  style:
      name: Style
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Test gofmt
          run: test -z $(go fmt ./...)

        - uses: dominikh/staticcheck-action@v1
          with:
              version: "latest"

        # this doesn't work why? i had to add the github action
        # - name: Install staticcheck
        #   run: go install honnef.co/go/tools/cmd/staticcheck@latest

        # - name: Run staticcheck
        #   run: staticcheck ./...
